// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSamadhaan.Infrastructure.Data;

#nullable disable

namespace eSamadhaan.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101132521_AddGrievanceEscalation")]
    partial class AddGrievanceEscalation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eSamadhaan.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_Name");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("GrievanceId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("GrievanceId")
                        .IsUnique()
                        .HasDatabaseName("IX_Feedbacks_GrievanceId");

                    b.HasIndex("Rating")
                        .HasDatabaseName("IX_Feedbacks_Rating");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("IX_Feedbacks_SubmittedAt");

                    b.ToTable("Feedbacks", (string)null);
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.Grievance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EscalationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrievanceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Grievances_CategoryId");

                    b.HasIndex("CitizenId")
                        .HasDatabaseName("IX_Grievances_CitizenId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Grievances_CreatedAt");

                    b.HasIndex("CurrentStatus")
                        .HasDatabaseName("IX_Grievances_CurrentStatus");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Grievances_DepartmentId");

                    b.HasIndex("GrievanceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Grievances_GrievanceNumber");

                    b.HasIndex("DepartmentId", "CurrentStatus")
                        .HasDatabaseName("IX_Grievances_DepartmentId_CurrentStatus");

                    b.ToTable("Grievances", (string)null);
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.GrievanceAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("GrievanceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OfficerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrievanceId")
                        .HasDatabaseName("IX_GrievanceAssignments_GrievanceId");

                    b.HasIndex("OfficerId")
                        .HasDatabaseName("IX_GrievanceAssignments_OfficerId");

                    b.HasIndex("GrievanceId", "IsActive")
                        .HasDatabaseName("IX_GrievanceAssignments_GrievanceId_IsActive");

                    b.HasIndex("OfficerId", "IsActive")
                        .HasDatabaseName("IX_GrievanceAssignments_OfficerId_IsActive");

                    b.ToTable("GrievanceAssignments", (string)null);
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.GrievanceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_GrievanceCategories_DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_GrievanceCategories_Name");

                    b.ToTable("GrievanceCategories", (string)null);
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.GrievanceResolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrievanceId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionRemarks")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ResolvedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ResolvedByOfficerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrievanceId")
                        .IsUnique()
                        .HasDatabaseName("IX_GrievanceResolutions_GrievanceId");

                    b.HasIndex("ResolvedAt")
                        .HasDatabaseName("IX_GrievanceResolutions_ResolvedAt");

                    b.HasIndex("ResolvedByOfficerId")
                        .HasDatabaseName("IX_GrievanceResolutions_ResolvedByOfficerId");

                    b.ToTable("GrievanceResolutions", (string)null);
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.GrievanceStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("GrievanceId")
                        .HasColumnType("int");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("IX_GrievanceStatusHistories_ChangedAt");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("IX_GrievanceStatusHistories_ChangedByUserId");

                    b.HasIndex("GrievanceId")
                        .HasDatabaseName("IX_GrievanceStatusHistories_GrievanceId");

                    b.HasIndex("GrievanceId", "ChangedAt")
                        .HasDatabaseName("IX_GrievanceStatusHistories_GrievanceId_ChangedAt");

                    b.ToTable("GrievanceStatusHistories", (string)null);
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Users_DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("eSamadhaan.Domain.Entities.Grievance", "Grievance")
                        .WithOne("Feedback")
                        .HasForeignKey("eSamadhaan.Domain.Entities.Feedback", "GrievanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grievance");
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.Grievance", b =>
                {
                    b.HasOne("eSamadhaan.Domain.Entities.GrievanceCategory", "Category")
                        .WithMany("Grievances")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eSamadhaan.Domain.Entities.User", "Citizen")
                        .WithMany("SubmittedGrievances")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eSamadhaan.Domain.Entities.Department", "Department")
                        .WithMany("Grievances")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Citizen");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.GrievanceAssignment", b =>
                {
                    b.HasOne("eSamadhaan.Domain.Entities.Grievance", "Grievance")
                        .WithMany("Assignments")
                        .HasForeignKey("GrievanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSamadhaan.Domain.Entities.User", "Officer")
                        .WithMany("Assignments")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grievance");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.GrievanceCategory", b =>
                {
                    b.HasOne("eSamadhaan.Domain.Entities.Department", "Department")
                        .WithMany("Categories")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.GrievanceResolution", b =>
                {
                    b.HasOne("eSamadhaan.Domain.Entities.Grievance", "Grievance")
                        .WithOne("Resolution")
                        .HasForeignKey("eSamadhaan.Domain.Entities.GrievanceResolution", "GrievanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSamadhaan.Domain.Entities.User", "ResolvedByOfficer")
                        .WithMany("Resolutions")
                        .HasForeignKey("ResolvedByOfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grievance");

                    b.Navigation("ResolvedByOfficer");
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.GrievanceStatusHistory", b =>
                {
                    b.HasOne("eSamadhaan.Domain.Entities.User", "ChangedByUser")
                        .WithMany("StatusChanges")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eSamadhaan.Domain.Entities.Grievance", "Grievance")
                        .WithMany("StatusHistory")
                        .HasForeignKey("GrievanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Grievance");
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.User", b =>
                {
                    b.HasOne("eSamadhaan.Domain.Entities.Department", "Department")
                        .WithMany("Officers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.Department", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Grievances");

                    b.Navigation("Officers");
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.Grievance", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Feedback");

                    b.Navigation("Resolution");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.GrievanceCategory", b =>
                {
                    b.Navigation("Grievances");
                });

            modelBuilder.Entity("eSamadhaan.Domain.Entities.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Resolutions");

                    b.Navigation("StatusChanges");

                    b.Navigation("SubmittedGrievances");
                });
#pragma warning restore 612, 618
        }
    }
}
